version: "2.1"

volumes:
  pihole_config:
  dnsmasq_config:
  duplicati:
  wireguard:

services:
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    network_mode: host

  # https://hub.docker.com/r/klutchell/unbound/
  unbound:
    build: ./unbound
    ports:
      - "5053:5053/udp"

  # https://hub.docker.com/r/linuxserver/wireguard/
  wireguard:
    build: wireguard
    privileged: true
    environment: 
      SERVERPORT: "51820"
    ports:
      - 51820:51820/udp
    volumes:
      - wireguard:/config
    labels:
      io.balena.features.kernel-modules: "1"
  
  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati:arm32v7-latest
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - 8200:8200/tcp
    volumes:
      - duplicati:/config
      - pihole_config:/source/pihole
      - dnsmasq_config:/source/dnsmasq
      - wireguard:/source/wireguard
